# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuPrincipal.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(806, 555)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/app.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 751, 271))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Edit_Filtro = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edit_Filtro.sizePolicy().hasHeightForWidth())
        self.Edit_Filtro.setSizePolicy(sizePolicy)
        self.Edit_Filtro.setObjectName(_fromUtf8("Edit_Filtro"))
        self.horizontalLayout.addWidget(self.Edit_Filtro)
        self.comboBox = QtGui.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.rb_ad = QtGui.QRadioButton(self.layoutWidget)
        self.rb_ad.setChecked(True)
        self.rb_ad.setObjectName(_fromUtf8("rb_ad"))
        self.horizontalLayout.addWidget(self.rb_ad)
        self.rb_pq = QtGui.QRadioButton(self.layoutWidget)
        self.rb_pq.setObjectName(_fromUtf8("rb_pq"))
        self.horizontalLayout.addWidget(self.rb_pq)
        spacerItem1 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tableWidget = QtGui.QTableView(self.layoutWidget)
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 300, 751, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edt_comentario = QtGui.QLineEdit(self.groupBox)
        self.edt_comentario.setObjectName(_fromUtf8("edt_comentario"))
        self.horizontalLayout_3.addWidget(self.edt_comentario)
        self.btn_agregarComentario = QtGui.QPushButton(self.groupBox)
        self.btn_agregarComentario.setObjectName(_fromUtf8("btn_agregarComentario"))
        self.horizontalLayout_3.addWidget(self.btn_agregarComentario)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 450, 761, 61))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btn_Alta = QtGui.QPushButton(self.layoutWidget1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/alta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Alta.setIcon(icon1)
        self.btn_Alta.setObjectName(_fromUtf8("btn_Alta"))
        self.horizontalLayout_2.addWidget(self.btn_Alta)
        self.btn_BorrarRegistro = QtGui.QPushButton(self.layoutWidget1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/baja.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_BorrarRegistro.setIcon(icon2)
        self.btn_BorrarRegistro.setObjectName(_fromUtf8("btn_BorrarRegistro"))
        self.horizontalLayout_2.addWidget(self.btn_BorrarRegistro)
        self.btn_Cambiar_Estado = QtGui.QPushButton(self.layoutWidget1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/cambio.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Cambiar_Estado.setIcon(icon3)
        self.btn_Cambiar_Estado.setObjectName(_fromUtf8("btn_Cambiar_Estado"))
        self.horizontalLayout_2.addWidget(self.btn_Cambiar_Estado)
        self.btn_Lista_Cerrados = QtGui.QPushButton(self.layoutWidget1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/lista.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Lista_Cerrados.setIcon(icon4)
        self.btn_Lista_Cerrados.setObjectName(_fromUtf8("btn_Lista_Cerrados"))
        self.horizontalLayout_2.addWidget(self.btn_Lista_Cerrados)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.menuBar.setFont(font)
        self.menuBar.setAutoFillBackground(True)
        self.menuBar.setStyleSheet(_fromUtf8(""))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuDirectivo = QtGui.QMenu(self.menuBar)
        self.menuDirectivo.setStyleSheet(_fromUtf8(""))
        self.menuDirectivo.setObjectName(_fromUtf8("menuDirectivo"))
        self.menuTickets = QtGui.QMenu(self.menuBar)
        self.menuTickets.setObjectName(_fromUtf8("menuTickets"))
        self.menuExportar = QtGui.QMenu(self.menuBar)
        self.menuExportar.setObjectName(_fromUtf8("menuExportar"))
        self.menuColegios = QtGui.QMenu(self.menuBar)
        self.menuColegios.setObjectName(_fromUtf8("menuColegios"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionCargar_Datos_Directivo = QtGui.QAction(MainWindow)
        self.actionCargar_Datos_Directivo.setObjectName(_fromUtf8("actionCargar_Datos_Directivo"))
        self.ainfor_cp = QtGui.QAction(MainWindow)
        self.ainfor_cp.setObjectName(_fromUtf8("ainfor_cp"))
        self.ainfor_cc = QtGui.QAction(MainWindow)
        self.ainfor_cc.setObjectName(_fromUtf8("ainfor_cc"))
        self.actionAbrir_carpeta_de_tickets = QtGui.QAction(MainWindow)
        self.actionAbrir_carpeta_de_tickets.setObjectName(_fromUtf8("actionAbrir_carpeta_de_tickets"))
        self.actionRetira_Servicio_Tecnico = QtGui.QAction(MainWindow)
        self.actionRetira_Servicio_Tecnico.setObjectName(_fromUtf8("actionRetira_Servicio_Tecnico"))
        self.actionEntrega_Servicio_Tecnico = QtGui.QAction(MainWindow)
        self.actionEntrega_Servicio_Tecnico.setObjectName(_fromUtf8("actionEntrega_Servicio_Tecnico"))
        self.actionTabla_Excel = QtGui.QAction(MainWindow)
        self.actionTabla_Excel.setObjectName(_fromUtf8("actionTabla_Excel"))
        self.actionTabla_ST_Parque_Escolar = QtGui.QAction(MainWindow)
        self.actionTabla_ST_Parque_Escolar.setObjectName(_fromUtf8("actionTabla_ST_Parque_Escolar"))
        self.actionTabla_Alumnos = QtGui.QAction(MainWindow)
        self.actionTabla_Alumnos.setObjectName(_fromUtf8("actionTabla_Alumnos"))
        self.actionTabla_Parque = QtGui.QAction(MainWindow)
        self.actionTabla_Parque.setObjectName(_fromUtf8("actionTabla_Parque"))
        self.actionRenovar_ticket_a = QtGui.QAction(MainWindow)
        self.actionRenovar_ticket_a.setObjectName(_fromUtf8("actionRenovar_ticket_a"))
        self.actionRenovar_Ticket_p = QtGui.QAction(MainWindow)
        self.actionRenovar_Ticket_p.setObjectName(_fromUtf8("actionRenovar_Ticket_p"))
        self.actionGenerar_Etiquetas = QtGui.QAction(MainWindow)
        self.actionGenerar_Etiquetas.setObjectName(_fromUtf8("actionGenerar_Etiquetas"))
        self.menuDirectivo.addAction(self.actionCargar_Datos_Directivo)
        self.menuTickets.addAction(self.actionAbrir_carpeta_de_tickets)
        self.menuTickets.addAction(self.actionRetira_Servicio_Tecnico)
        self.menuTickets.addAction(self.actionEntrega_Servicio_Tecnico)
        self.menuTickets.addAction(self.actionRenovar_ticket_a)
        self.menuTickets.addAction(self.actionRenovar_Ticket_p)
        self.menuExportar.addAction(self.actionTabla_Excel)
        self.menuExportar.addAction(self.actionTabla_ST_Parque_Escolar)
        self.menuExportar.addAction(self.actionTabla_Alumnos)
        self.menuExportar.addAction(self.actionTabla_Parque)
        self.menuColegios.addAction(self.actionGenerar_Etiquetas)
        self.menuBar.addAction(self.menuDirectivo.menuAction())
        self.menuBar.addAction(self.menuTickets.menuAction())
        self.menuBar.addAction(self.menuExportar.menuAction())
        self.menuBar.addAction(self.menuColegios.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox, self.Edit_Filtro)
        MainWindow.setTabOrder(self.Edit_Filtro, self.btn_Alta)
        MainWindow.setTabOrder(self.btn_Alta, self.btn_BorrarRegistro)
        MainWindow.setTabOrder(self.btn_BorrarRegistro, self.btn_Cambiar_Estado)
        MainWindow.setTabOrder(self.btn_Cambiar_Estado, self.btn_Lista_Cerrados)
        MainWindow.setTabOrder(self.btn_Lista_Cerrados, self.plainTextEdit)
        MainWindow.setTabOrder(self.plainTextEdit, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.rb_ad)
        MainWindow.setTabOrder(self.rb_ad, self.rb_pq)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Programa de Gestion de ST", None))
        self.rb_ad.setText(_translate("MainWindow", "Alumnos / Docentes", None))
        self.rb_pq.setText(_translate("MainWindow", "Parque Escolar", None))
        self.groupBox.setTitle(_translate("MainWindow", "Detalle", None))
        self.btn_agregarComentario.setText(_translate("MainWindow", "Agregar Comentario", None))
        self.btn_Alta.setText(_translate("MainWindow", "Alta de Ticket", None))
        self.btn_BorrarRegistro.setText(_translate("MainWindow", "Eliminar Ticket", None))
        self.btn_Cambiar_Estado.setText(_translate("MainWindow", "Cambiar estado de ticket", None))
        self.btn_Lista_Cerrados.setText(_translate("MainWindow", "Listado de casos cerrados", None))
        self.menuDirectivo.setTitle(_translate("MainWindow", "Directivo", None))
        self.menuTickets.setTitle(_translate("MainWindow", "Tickets", None))
        self.menuExportar.setTitle(_translate("MainWindow", "Exportar", None))
        self.menuColegios.setTitle(_translate("MainWindow", "Colegios", None))
        self.actionCargar_Datos_Directivo.setText(_translate("MainWindow", "Cargar Datos Directivo", None))
        self.ainfor_cp.setText(_translate("MainWindow", "Informe de Casos Pendientes", None))
        self.ainfor_cc.setText(_translate("MainWindow", "Informe de Casos Cerrados", None))
        self.actionAbrir_carpeta_de_tickets.setText(_translate("MainWindow", "Abrir carpeta de tickets", None))
        self.actionRetira_Servicio_Tecnico.setText(_translate("MainWindow", "Retira Servicio Tecnico", None))
        self.actionEntrega_Servicio_Tecnico.setText(_translate("MainWindow", "Entrega Servicio Tecnico", None))
        self.actionTabla_Excel.setText(_translate("MainWindow", "Tabla ST Alu/Doc", None))
        self.actionTabla_ST_Parque_Escolar.setText(_translate("MainWindow", "Tabla ST Parque Escolar", None))
        self.actionTabla_Alumnos.setText(_translate("MainWindow", "Tabla Alumnos", None))
        self.actionTabla_Parque.setText(_translate("MainWindow", "Tabla Parque", None))
        self.actionRenovar_ticket_a.setText(_translate("MainWindow", "Renovar Ticket Alumno", None))
        self.actionRenovar_Ticket_p.setText(_translate("MainWindow", "Renovar Ticket Parque", None))
        self.actionGenerar_Etiquetas.setText(_translate("MainWindow", "Generar Etiquetas", None))

import resource_rc
