# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormModiDir.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogModi(object):
    def setupUi(self, DialogModi):
        DialogModi.setObjectName(_fromUtf8("DialogModi"))
        DialogModi.resize(439, 478)
        self.layoutWidget = QtGui.QWidget(DialogModi)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 20, 393, 431))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.Edit_CUIL = QtGui.QLineEdit(self.layoutWidget)
        self.Edit_CUIL.setObjectName(_fromUtf8("Edit_CUIL"))
        self.horizontalLayout_2.addWidget(self.Edit_CUIL)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.Edit_AyN = QtGui.QLineEdit(self.layoutWidget)
        self.Edit_AyN.setObjectName(_fromUtf8("Edit_AyN"))
        self.horizontalLayout.addWidget(self.Edit_AyN)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Edit_Dom = QtGui.QLineEdit(self.layoutWidget)
        self.Edit_Dom.setObjectName(_fromUtf8("Edit_Dom"))
        self.horizontalLayout_3.addWidget(self.Edit_Dom)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.Edit_Tel = QtGui.QLineEdit(self.layoutWidget)
        self.Edit_Tel.setObjectName(_fromUtf8("Edit_Tel"))
        self.horizontalLayout_4.addWidget(self.Edit_Tel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.Edit_Mail = QtGui.QLineEdit(self.layoutWidget)
        self.Edit_Mail.setObjectName(_fromUtf8("Edit_Mail"))
        self.horizontalLayout_5.addWidget(self.Edit_Mail)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.cmb_CUE = QtGui.QComboBox(self.layoutWidget)
        self.cmb_CUE.setObjectName(_fromUtf8("cmb_CUE"))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.cmb_CUE.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.cmb_CUE)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.btn_Modificar = QtGui.QPushButton(self.layoutWidget)
        self.btn_Modificar.setObjectName(_fromUtf8("btn_Modificar"))
        self.horizontalLayout_6.addWidget(self.btn_Modificar)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(DialogModi)
        QtCore.QMetaObject.connectSlotsByName(DialogModi)

    def retranslateUi(self, DialogModi):
        DialogModi.setWindowTitle(_translate("DialogModi", "Modificar Datos Directivo", None))
        self.label_5.setText(_translate("DialogModi", "CUIL", None))
        self.label_2.setText(_translate("DialogModi", "Apellidos y Nombres", None))
        self.label_3.setText(_translate("DialogModi", "Domicilio", None))
        self.label_4.setText(_translate("DialogModi", "Tel de contacto / Cel", None))
        self.label_9.setText(_translate("DialogModi", "Mail (Opcional)", None))
        self.label_10.setText(_translate("DialogModi", "CUE", None))
        self.cmb_CUE.setItemText(0, _translate("DialogModi", "940015000", None))
        self.cmb_CUE.setItemText(1, _translate("DialogModi", "940009200", None))
        self.cmb_CUE.setItemText(2, _translate("DialogModi", "940002500", None))
        self.cmb_CUE.setItemText(3, _translate("DialogModi", "940002600", None))
        self.cmb_CUE.setItemText(4, _translate("DialogModi", "940001700", None))
        self.cmb_CUE.setItemText(5, _translate("DialogModi", "940007700", None))
        self.cmb_CUE.setItemText(6, _translate("DialogModi", "940011400", None))
        self.cmb_CUE.setItemText(7, _translate("DialogModi", "940011500", None))
        self.cmb_CUE.setItemText(8, _translate("DialogModi", "940015700", None))
        self.cmb_CUE.setItemText(9, _translate("DialogModi", "940001900", None))
        self.cmb_CUE.setItemText(10, _translate("DialogModi", "940016200", None))
        self.cmb_CUE.setItemText(11, _translate("DialogModi", "940006400", None))
        self.cmb_CUE.setItemText(12, _translate("DialogModi", "940017800", None))
        self.cmb_CUE.setItemText(13, _translate("DialogModi", "940007100", None))
        self.cmb_CUE.setItemText(14, _translate("DialogModi", "940002700", None))
        self.cmb_CUE.setItemText(15, _translate("DialogModi", "940017900", None))
        self.cmb_CUE.setItemText(16, _translate("DialogModi", "940019700", None))
        self.cmb_CUE.setItemText(17, _translate("DialogModi", "940015600", None))
        self.cmb_CUE.setItemText(18, _translate("DialogModi", "940016400", None))
        self.cmb_CUE.setItemText(19, _translate("DialogModi", "940018900", None))
        self.cmb_CUE.setItemText(20, _translate("DialogModi", "940007600", None))
        self.cmb_CUE.setItemText(21, _translate("DialogModi", "940008300", None))
        self.cmb_CUE.setItemText(22, _translate("DialogModi", "940008400", None))
        self.cmb_CUE.setItemText(23, _translate("DialogModi", "940008500", None))
        self.cmb_CUE.setItemText(24, _translate("DialogModi", "940008800", None))
        self.cmb_CUE.setItemText(25, _translate("DialogModi", "940006100", None))
        self.cmb_CUE.setItemText(26, _translate("DialogModi", "940016900", None))
        self.cmb_CUE.setItemText(27, _translate("DialogModi", "940015900", None))
        self.cmb_CUE.setItemText(28, _translate("DialogModi", "940015800", None))
        self.cmb_CUE.setItemText(29, _translate("DialogModi", "940015801", None))
        self.btn_Modificar.setText(_translate("DialogModi", "Insertar", None))

