# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormModiTicketParque.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_Parque(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(716, 375)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/alta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 301, 331))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 23, 271, 125))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.Edit_Ticket = QtGui.QLineEdit(self.layoutWidget1)
        self.Edit_Ticket.setObjectName(_fromUtf8("Edit_Ticket"))
        self.horizontalLayout.addWidget(self.Edit_Ticket)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_23 = QtGui.QLabel(self.layoutWidget1)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_3.addWidget(self.label_23)
        self.cmb_condicion = QtGui.QComboBox(self.layoutWidget1)
        self.cmb_condicion.setObjectName(_fromUtf8("cmb_condicion"))
        self.cmb_condicion.addItem(_fromUtf8(""))
        self.cmb_condicion.addItem(_fromUtf8(""))
        self.cmb_condicion.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.cmb_condicion)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.Fecha_Conig = QtGui.QDateEdit(self.layoutWidget1)
        self.Fecha_Conig.setDate(QtCore.QDate(2016, 1, 19))
        self.Fecha_Conig.setCalendarPopup(True)
        self.Fecha_Conig.setTimeSpec(QtCore.Qt.LocalTime)
        self.Fecha_Conig.setObjectName(_fromUtf8("Fecha_Conig"))
        self.horizontalLayout_11.addWidget(self.Fecha_Conig)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 24, 271, 101))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.Edit_N_S = QtGui.QLineEdit(self.layoutWidget2)
        self.Edit_N_S.setObjectName(_fromUtf8("Edit_N_S"))
        self.horizontalLayout_3.addWidget(self.Edit_N_S)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.Edit_Marca = QtGui.QLineEdit(self.layoutWidget2)
        self.Edit_Marca.setObjectName(_fromUtf8("Edit_Marca"))
        self.horizontalLayout_9.addWidget(self.Edit_Marca)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        self.Edit_Modelo = QtGui.QLineEdit(self.layoutWidget2)
        self.Edit_Modelo.setObjectName(_fromUtf8("Edit_Modelo"))
        self.horizontalLayout_10.addWidget(self.Edit_Modelo)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 32, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(48, 130, 231, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setBaseSize(QtCore.QSize(100, 1000))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.groupBox)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(330, 180, 341, 161))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Edit_Comentarios = QtGui.QLineEdit(self.groupBox_3)
        self.Edit_Comentarios.setObjectName(_fromUtf8("Edit_Comentarios"))
        self.verticalLayout_2.addWidget(self.Edit_Comentarios)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btn_Editar = QtGui.QPushButton(self.widget)
        self.btn_Editar.setObjectName(_fromUtf8("btn_Editar"))
        self.horizontalLayout_4.addWidget(self.btn_Editar)
        self.btn_Cancelar = QtGui.QPushButton(self.widget)
        self.btn_Cancelar.setObjectName(_fromUtf8("btn_Cancelar"))
        self.horizontalLayout_4.addWidget(self.btn_Cancelar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.Edit_Ticket, self.Fecha_Conig)
        Dialog.setTabOrder(self.Fecha_Conig, self.Edit_N_S)
        Dialog.setTabOrder(self.Edit_N_S, self.Edit_Marca)
        Dialog.setTabOrder(self.Edit_Marca, self.Edit_Modelo)
        Dialog.setTabOrder(self.Edit_Modelo, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.Edit_Comentarios)
        Dialog.setTabOrder(self.Edit_Comentarios, self.btn_Editar)
        Dialog.setTabOrder(self.btn_Editar, self.btn_Cancelar)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Modificacion de Tickets", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Datos CONIG", None))
        self.label_10.setText(_translate("Dialog", "N° de Ticket (CONIG)", None))
        self.label_23.setText(_translate("Dialog", "CONDICION DEL EQUIPO", None))
        self.cmb_condicion.setItemText(0, _translate("Dialog", "PRESTAMO", None))
        self.cmb_condicion.setItemText(1, _translate("Dialog", "USO ESCOLAR", None))
        self.cmb_condicion.setItemText(2, _translate("Dialog", "PARA REASIGNAR", None))
        self.label_11.setText(_translate("Dialog", "Fecha Conig", None))
        self.groupBox.setTitle(_translate("Dialog", "Datos Maquina", None))
        self.label_7.setText(_translate("Dialog", "Numero de Serie", None))
        self.label_6.setText(_translate("Dialog", "Marca", None))
        self.label_5.setText(_translate("Dialog", "Modelo", None))
        self.label_8.setText(_translate("Dialog", "Motivo", None))
        self.comboBox.setItemText(0, _translate("Dialog", "EL DISPLAY TIENE PIXELES DAÑADOS", None))
        self.comboBox.setItemText(1, _translate("Dialog", "EL EQUIPO NO ENCIENDE", None))
        self.comboBox.setItemText(2, _translate("Dialog", "TECLADO NO FUNCIONA", None))
        self.comboBox.setItemText(3, _translate("Dialog", "ERROR DE DISCO RIGIDO", None))
        self.comboBox.setItemText(4, _translate("Dialog", "LA PANTALLA NO FUNCIONA", None))
        self.comboBox.setItemText(5, _translate("Dialog", "PANTALLA ROTA", None))
        self.comboBox.setItemText(6, _translate("Dialog", "PROBLEMAS DE BATERIA", None))
        self.comboBox.setItemText(7, _translate("Dialog", "PROBLEMAS DE SOFTWARE", None))
        self.comboBox.setItemText(8, _translate("Dialog", "FALLA DE CARGADOR", None))
        self.comboBox.setItemText(9, _translate("Dialog", "CARGADOR CON DAÑOS FISICOS", None))
        self.comboBox.setItemText(10, _translate("Dialog", "NO CARGA LA BATERIA", None))
        self.comboBox.setItemText(11, _translate("Dialog", "FALLA DE ACTUALIZACIÓN DE BIOS", None))
        self.comboBox.setItemText(12, _translate("Dialog", "TECLADO ROTO", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Detalle del caso", None))
        self.btn_Editar.setText(_translate("Dialog", "Editar", None))
        self.btn_Cancelar.setText(_translate("Dialog", "Cancelar", None))

import resource_rc
