# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormAlta.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(738, 469)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/alta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 701, 391))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 291, 171))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 24, 271, 101))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.Edit_N_S = QtGui.QLineEdit(self.layoutWidget)
        self.Edit_N_S.setObjectName(_fromUtf8("Edit_N_S"))
        self.horizontalLayout_3.addWidget(self.Edit_N_S)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.Edit_Marca = QtGui.QLineEdit(self.layoutWidget)
        self.Edit_Marca.setObjectName(_fromUtf8("Edit_Marca"))
        self.horizontalLayout_9.addWidget(self.Edit_Marca)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        self.Edit_Modelo = QtGui.QLineEdit(self.layoutWidget)
        self.Edit_Modelo.setObjectName(_fromUtf8("Edit_Modelo"))
        self.horizontalLayout_10.addWidget(self.Edit_Modelo)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 32, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(48, 130, 231, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setBaseSize(QtCore.QSize(100, 1000))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 280, 371, 51))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.btn_Limpiar = QtGui.QPushButton(self.layoutWidget1)
        self.btn_Limpiar.setObjectName(_fromUtf8("btn_Limpiar"))
        self.horizontalLayout_14.addWidget(self.btn_Limpiar)
        self.btn_Editar = QtGui.QPushButton(self.layoutWidget1)
        self.btn_Editar.setObjectName(_fromUtf8("btn_Editar"))
        self.horizontalLayout_14.addWidget(self.btn_Editar)
        self.btn_Generar = QtGui.QPushButton(self.layoutWidget1)
        self.btn_Generar.setObjectName(_fromUtf8("btn_Generar"))
        self.horizontalLayout_14.addWidget(self.btn_Generar)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(310, 200, 371, 71))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.Edit_Comentarios = QtGui.QLineEdit(self.groupBox_3)
        self.Edit_Comentarios.setObjectName(_fromUtf8("Edit_Comentarios"))
        self.verticalLayout_4.addWidget(self.Edit_Comentarios)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 10, 371, 191))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 24, 341, 151))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.Edit_AyN = QtGui.QLineEdit(self.layoutWidget2)
        self.Edit_AyN.setObjectName(_fromUtf8("Edit_AyN"))
        self.horizontalLayout_5.addWidget(self.Edit_AyN)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.Edit_Dom = QtGui.QLineEdit(self.layoutWidget2)
        self.Edit_Dom.setObjectName(_fromUtf8("Edit_Dom"))
        self.horizontalLayout_6.addWidget(self.Edit_Dom)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.Edit_Tel = QtGui.QLineEdit(self.layoutWidget2)
        self.Edit_Tel.setObjectName(_fromUtf8("Edit_Tel"))
        self.horizontalLayout_7.addWidget(self.Edit_Tel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.layoutWidget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.Edit_Mail = QtGui.QLineEdit(self.layoutWidget2)
        self.Edit_Mail.setObjectName(_fromUtf8("Edit_Mail"))
        self.horizontalLayout_8.addWidget(self.Edit_Mail)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 291, 141))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 23, 271, 111))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(self.layoutWidget3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.Edit_Ticket = QtGui.QLineEdit(self.layoutWidget3)
        self.Edit_Ticket.setObjectName(_fromUtf8("Edit_Ticket"))
        self.horizontalLayout.addWidget(self.Edit_Ticket)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.Edit_CUIT = QtGui.QLineEdit(self.layoutWidget3)
        self.Edit_CUIT.setObjectName(_fromUtf8("Edit_CUIT"))
        self.horizontalLayout_2.addWidget(self.Edit_CUIT)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.btn_buscar = QtGui.QPushButton(self.layoutWidget3)
        self.btn_buscar.setObjectName(_fromUtf8("btn_buscar"))
        self.verticalLayout_3.addWidget(self.btn_buscar)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.layoutWidget3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.Fecha_Conig = QtGui.QDateEdit(self.layoutWidget3)
        self.Fecha_Conig.setDate(QtCore.QDate(2016, 1, 19))
        self.Fecha_Conig.setCalendarPopup(True)
        self.Fecha_Conig.setTimeSpec(QtCore.Qt.LocalTime)
        self.Fecha_Conig.setObjectName(_fromUtf8("Fecha_Conig"))
        self.horizontalLayout_11.addWidget(self.Fecha_Conig)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 180, 291, 181))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(11, 24, 271, 128))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_12 = QtGui.QLabel(self.layoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.Edit_N_S_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.Edit_N_S_2.setObjectName(_fromUtf8("Edit_N_S_2"))
        self.horizontalLayout_4.addWidget(self.Edit_N_S_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.btn_Buscar_par = QtGui.QPushButton(self.layoutWidget_2)
        self.btn_Buscar_par.setObjectName(_fromUtf8("btn_Buscar_par"))
        self.verticalLayout_5.addWidget(self.btn_Buscar_par)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_13 = QtGui.QLabel(self.layoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_12.addWidget(self.label_13)
        self.Edit_Marca_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.Edit_Marca_2.setObjectName(_fromUtf8("Edit_Marca_2"))
        self.horizontalLayout_12.addWidget(self.Edit_Marca_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_14 = QtGui.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_13.addWidget(self.label_14)
        self.Edit_Modelo_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.Edit_Modelo_2.setObjectName(_fromUtf8("Edit_Modelo_2"))
        self.horizontalLayout_13.addWidget(self.Edit_Modelo_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(12, 160, 32, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 160, 231, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setBaseSize(QtCore.QSize(100, 1000))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.layoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(310, 280, 371, 51))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.btn_Limpiar_par = QtGui.QPushButton(self.layoutWidget_3)
        self.btn_Limpiar_par.setObjectName(_fromUtf8("btn_Limpiar_par"))
        self.horizontalLayout_15.addWidget(self.btn_Limpiar_par)
        self.btn_Editar_par = QtGui.QPushButton(self.layoutWidget_3)
        self.btn_Editar_par.setObjectName(_fromUtf8("btn_Editar_par"))
        self.horizontalLayout_15.addWidget(self.btn_Editar_par)
        self.btn_Generar_2 = QtGui.QPushButton(self.layoutWidget_3)
        self.btn_Generar_2.setObjectName(_fromUtf8("btn_Generar_2"))
        self.horizontalLayout_15.addWidget(self.btn_Generar_2)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(310, 10, 371, 191))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget_4.setGeometry(QtCore.QRect(11, 24, 341, 151))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_16 = QtGui.QLabel(self.layoutWidget_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_16.addWidget(self.label_16)
        self.Edit_AyN_2 = QtGui.QLineEdit(self.layoutWidget_4)
        self.Edit_AyN_2.setObjectName(_fromUtf8("Edit_AyN_2"))
        self.horizontalLayout_16.addWidget(self.Edit_AyN_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_17 = QtGui.QLabel(self.layoutWidget_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_17.addWidget(self.label_17)
        self.Edit_Dom_2 = QtGui.QLineEdit(self.layoutWidget_4)
        self.Edit_Dom_2.setObjectName(_fromUtf8("Edit_Dom_2"))
        self.horizontalLayout_17.addWidget(self.Edit_Dom_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_18 = QtGui.QLabel(self.layoutWidget_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_18.addWidget(self.label_18)
        self.Edit_Tel_2 = QtGui.QLineEdit(self.layoutWidget_4)
        self.Edit_Tel_2.setObjectName(_fromUtf8("Edit_Tel_2"))
        self.horizontalLayout_18.addWidget(self.Edit_Tel_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_19 = QtGui.QLabel(self.layoutWidget_4)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_19.addWidget(self.label_19)
        self.Edit_Mail_2 = QtGui.QLineEdit(self.layoutWidget_4)
        self.Edit_Mail_2.setObjectName(_fromUtf8("Edit_Mail_2"))
        self.horizontalLayout_19.addWidget(self.Edit_Mail_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 291, 161))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 23, 271, 125))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_20 = QtGui.QLabel(self.layoutWidget_5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_20.addWidget(self.label_20)
        self.Edit_Ticket_2 = QtGui.QLineEdit(self.layoutWidget_5)
        self.Edit_Ticket_2.setObjectName(_fromUtf8("Edit_Ticket_2"))
        self.horizontalLayout_20.addWidget(self.Edit_Ticket_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_21 = QtGui.QLabel(self.layoutWidget_5)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_21.addWidget(self.label_21)
        self.Edit_CUIT_2 = QtGui.QLineEdit(self.layoutWidget_5)
        self.Edit_CUIT_2.setObjectName(_fromUtf8("Edit_CUIT_2"))
        self.horizontalLayout_21.addWidget(self.Edit_CUIT_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.label_23 = QtGui.QLabel(self.layoutWidget_5)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_7.addWidget(self.label_23)
        self.cmb_condicion = QtGui.QComboBox(self.layoutWidget_5)
        self.cmb_condicion.setObjectName(_fromUtf8("cmb_condicion"))
        self.cmb_condicion.addItem(_fromUtf8(""))
        self.cmb_condicion.addItem(_fromUtf8(""))
        self.cmb_condicion.addItem(_fromUtf8(""))
        self.verticalLayout_7.addWidget(self.cmb_condicion)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_22 = QtGui.QLabel(self.layoutWidget_5)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_22.addWidget(self.label_22)
        self.Fecha_Conig_2 = QtGui.QDateEdit(self.layoutWidget_5)
        self.Fecha_Conig_2.setDate(QtCore.QDate(2016, 1, 19))
        self.Fecha_Conig_2.setCalendarPopup(True)
        self.Fecha_Conig_2.setTimeSpec(QtCore.Qt.LocalTime)
        self.Fecha_Conig_2.setObjectName(_fromUtf8("Fecha_Conig_2"))
        self.horizontalLayout_22.addWidget(self.Fecha_Conig_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(310, 210, 371, 71))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.Edit_Comentarios_2 = QtGui.QLineEdit(self.groupBox_8)
        self.Edit_Comentarios_2.setObjectName(_fromUtf8("Edit_Comentarios_2"))
        self.verticalLayout_8.addWidget(self.Edit_Comentarios_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.Edit_Ticket, self.Edit_CUIT)
        Dialog.setTabOrder(self.Edit_CUIT, self.btn_buscar)
        Dialog.setTabOrder(self.btn_buscar, self.Fecha_Conig)
        Dialog.setTabOrder(self.Fecha_Conig, self.Edit_N_S)
        Dialog.setTabOrder(self.Edit_N_S, self.Edit_Marca)
        Dialog.setTabOrder(self.Edit_Marca, self.Edit_Modelo)
        Dialog.setTabOrder(self.Edit_Modelo, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.Edit_AyN)
        Dialog.setTabOrder(self.Edit_AyN, self.Edit_Dom)
        Dialog.setTabOrder(self.Edit_Dom, self.Edit_Tel)
        Dialog.setTabOrder(self.Edit_Tel, self.Edit_Mail)
        Dialog.setTabOrder(self.Edit_Mail, self.Edit_Comentarios)
        Dialog.setTabOrder(self.Edit_Comentarios, self.btn_Limpiar)
        Dialog.setTabOrder(self.btn_Limpiar, self.btn_Editar)
        Dialog.setTabOrder(self.btn_Editar, self.btn_Generar)
        Dialog.setTabOrder(self.btn_Generar, self.Edit_Ticket_2)
        Dialog.setTabOrder(self.Edit_Ticket_2, self.Edit_CUIT_2)
        Dialog.setTabOrder(self.Edit_CUIT_2, self.cmb_condicion)
        Dialog.setTabOrder(self.cmb_condicion, self.Fecha_Conig_2)
        Dialog.setTabOrder(self.Fecha_Conig_2, self.Edit_N_S_2)
        Dialog.setTabOrder(self.Edit_N_S_2, self.btn_Buscar_par)
        Dialog.setTabOrder(self.btn_Buscar_par, self.Edit_Marca_2)
        Dialog.setTabOrder(self.Edit_Marca_2, self.Edit_Modelo_2)
        Dialog.setTabOrder(self.Edit_Modelo_2, self.comboBox_2)
        Dialog.setTabOrder(self.comboBox_2, self.Edit_AyN_2)
        Dialog.setTabOrder(self.Edit_AyN_2, self.Edit_Dom_2)
        Dialog.setTabOrder(self.Edit_Dom_2, self.Edit_Tel_2)
        Dialog.setTabOrder(self.Edit_Tel_2, self.Edit_Mail_2)
        Dialog.setTabOrder(self.Edit_Mail_2, self.Edit_Comentarios_2)
        Dialog.setTabOrder(self.Edit_Comentarios_2, self.btn_Limpiar_par)
        Dialog.setTabOrder(self.btn_Limpiar_par, self.btn_Editar_par)
        Dialog.setTabOrder(self.btn_Editar_par, self.btn_Generar_2)
        Dialog.setTabOrder(self.btn_Generar_2, self.tabWidget)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Alta de Servicio Tecnico", None))
        self.groupBox.setTitle(_translate("Dialog", "Datos Maquina", None))
        self.label_7.setText(_translate("Dialog", "Numero de Serie", None))
        self.label_6.setText(_translate("Dialog", "Marca", None))
        self.label_5.setText(_translate("Dialog", "Modelo", None))
        self.label_8.setText(_translate("Dialog", "Motivo", None))
        self.comboBox.setItemText(0, _translate("Dialog", "EL DISPLAY TIENE PIXELES DAÑADOS", None))
        self.comboBox.setItemText(1, _translate("Dialog", "EL EQUIPO NO ENCIENDE", None))
        self.comboBox.setItemText(2, _translate("Dialog", "TECLADO NO FUNCIONA", None))
        self.comboBox.setItemText(3, _translate("Dialog", "ERROR DE DISCO RIGIDO", None))
        self.comboBox.setItemText(4, _translate("Dialog", "LA PANTALLA NO FUNCIONA", None))
        self.comboBox.setItemText(5, _translate("Dialog", "PANTALLA ROTA", None))
        self.comboBox.setItemText(6, _translate("Dialog", "PROBLEMAS DE BATERIA", None))
        self.comboBox.setItemText(7, _translate("Dialog", "PROBLEMAS DE SOFTWARE", None))
        self.comboBox.setItemText(8, _translate("Dialog", "FALLA DE CARGADOR", None))
        self.comboBox.setItemText(9, _translate("Dialog", "CARGADOR CON DAÑOS FISICOS", None))
        self.comboBox.setItemText(10, _translate("Dialog", "NO CARGA LA BATERIA", None))
        self.comboBox.setItemText(11, _translate("Dialog", "FALLA DE ACTUALIZACIÓN DE BIOS", None))
        self.comboBox.setItemText(12, _translate("Dialog", "TECLADO ROTO\n"
"", None))
        self.btn_Limpiar.setText(_translate("Dialog", "Limpiar", None))
        self.btn_Editar.setText(_translate("Dialog", "Editar", None))
        self.btn_Generar.setText(_translate("Dialog", "Generar", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Detalle del caso", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Datos Alumno", None))
        self.label_2.setText(_translate("Dialog", "Apellidos y Nombres", None))
        self.label_3.setText(_translate("Dialog", "Domicilio", None))
        self.label_4.setText(_translate("Dialog", "Tel de contacto / Cel", None))
        self.label_9.setText(_translate("Dialog", "Mail (Opcional)", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Datos CONIG", None))
        self.label_10.setText(_translate("Dialog", "N° de Ticket (CONIG)", None))
        self.label.setText(_translate("Dialog", "CUIL", None))
        self.btn_buscar.setText(_translate("Dialog", "Buscar", None))
        self.label_11.setText(_translate("Dialog", "Fecha Conig", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Alumno / Docente", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Datos Maquina", None))
        self.label_12.setText(_translate("Dialog", "Numero de Serie", None))
        self.btn_Buscar_par.setText(_translate("Dialog", "Buscar", None))
        self.label_13.setText(_translate("Dialog", "Marca", None))
        self.label_14.setText(_translate("Dialog", "Modelo", None))
        self.label_15.setText(_translate("Dialog", "Motivo", None))
        self.comboBox_2.setItemText(0, _translate("Dialog", "EL DISPLAY TIENE PIXELES DAÑADOS", None))
        self.comboBox_2.setItemText(1, _translate("Dialog", "EL EQUIPO NO ENCIENDE", None))
        self.comboBox_2.setItemText(2, _translate("Dialog", "TECLADO NO FUNCIONA", None))
        self.comboBox_2.setItemText(3, _translate("Dialog", "ERROR DE DISCO RIGIDO", None))
        self.comboBox_2.setItemText(4, _translate("Dialog", "LA PANTALLA NO FUNCIONA", None))
        self.comboBox_2.setItemText(5, _translate("Dialog", "PANTALLA ROTA", None))
        self.comboBox_2.setItemText(6, _translate("Dialog", "PROBLEMAS DE BATERIA", None))
        self.comboBox_2.setItemText(7, _translate("Dialog", "PROBLEMAS DE SOFTWARE", None))
        self.comboBox_2.setItemText(8, _translate("Dialog", "FALLA DE CARGADOR", None))
        self.comboBox_2.setItemText(9, _translate("Dialog", "CARGADOR CON DAÑOS FISICOS", None))
        self.comboBox_2.setItemText(10, _translate("Dialog", "NO CARGA LA BATERIA", None))
        self.comboBox_2.setItemText(11, _translate("Dialog", "FALLA DE ACTUALIZACIÓN DE BIOS", None))
        self.comboBox_2.setItemText(12, _translate("Dialog", "TECLADO ROTO\n"
"", None))
        self.btn_Limpiar_par.setText(_translate("Dialog", "Limpiar", None))
        self.btn_Editar_par.setText(_translate("Dialog", "Editar", None))
        self.btn_Generar_2.setText(_translate("Dialog", "Generar", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Datos Directivo / Establecimiento", None))
        self.label_16.setText(_translate("Dialog", "Apellidos y Nombres", None))
        self.label_17.setText(_translate("Dialog", "Domicilio", None))
        self.label_18.setText(_translate("Dialog", "Tel de contacto / Cel", None))
        self.label_19.setText(_translate("Dialog", "Mail (Opcional)", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Datos CONIG", None))
        self.label_20.setText(_translate("Dialog", "N° de Ticket (CONIG)", None))
        self.label_21.setText(_translate("Dialog", "CUIL", None))
        self.label_23.setText(_translate("Dialog", "CONDICION DEL EQUIPO", None))
        self.cmb_condicion.setItemText(0, _translate("Dialog", "PRESTAMO", None))
        self.cmb_condicion.setItemText(1, _translate("Dialog", "USO ESCOLAR", None))
        self.cmb_condicion.setItemText(2, _translate("Dialog", "PARA REASIGNAR", None))
        self.label_22.setText(_translate("Dialog", "Fecha Conig", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Detalle del caso", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Parque Escolar / Directivo", None))

import resource_rc
